apiVersion: v1
kind: Namespace
metadata:
  name: database
  lables:
    name: database
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-cluster
spec:
  instances: 3

  storage:
    size: 1Gi
